/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boutemineoualid.gephi.plugins.clustering.label_propagation;

import javax.swing.JPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//boutemineoualid.gephi.plugins.clustering.label_propagation//LabelPropagationSettingsPanel//EN",
        autostore = false
)
@ActionID(category = "Window", id = "boutemineoualid.gephi.plugins.clustering.label_propagation.LabelPropagationSettingsPanelTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@Messages({
    "CTL_LabelPropagationSettingsPanelAction=LabelPropagationSettingsPanel",
    "CTL_LabelPropagationSettingsPanelTopComponent=LabelPropagationSettingsPanel Window",
    "HINT_LabelPropagationSettingsPanelTopComponent=This is a LabelPropagationSettingsPanel window"
})
public final class LabelPropagationSettingsPanel extends JPanel {

    public LabelPropagationSettingsPanel() {
        initComponents();
        this.txtAnimationTimeSpan.setText("1000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkAnimateLabelPropagation = new javax.swing.JCheckBox();
        lblAnimationTimeSpan = new javax.swing.JLabel();
        txtAnimationTimeSpan = new javax.swing.JFormattedTextField();

        org.openide.awt.Mnemonics.setLocalizedText(chkAnimateLabelPropagation, org.openide.util.NbBundle.getMessage(LabelPropagationSettingsPanel.class, "LabelPropagationSettingsPanel.chkAnimateLabelPropagation.text")); // NOI18N
        chkAnimateLabelPropagation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkAnimateLabelPropagation.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkAnimateLabelPropagation.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        chkAnimateLabelPropagation.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        chkAnimateLabelPropagation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkAnimateLabelPropagationStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblAnimationTimeSpan, org.openide.util.NbBundle.getMessage(LabelPropagationSettingsPanel.class, "LabelPropagationSettingsPanel.lblAnimationTimeSpan.text")); // NOI18N
        lblAnimationTimeSpan.setEnabled(false);
        lblAnimationTimeSpan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblAnimationTimeSpan.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtAnimationTimeSpan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        txtAnimationTimeSpan.setText(org.openide.util.NbBundle.getMessage(LabelPropagationSettingsPanel.class, "LabelPropagationSettingsPanel.txtAnimationTimeSpan.text")); // NOI18N
        txtAnimationTimeSpan.setToolTipText(org.openide.util.NbBundle.getMessage(LabelPropagationSettingsPanel.class, "LabelPropagationSettingsPanel.txtAnimationTimeSpan.toolTipText")); // NOI18N
        txtAnimationTimeSpan.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkAnimateLabelPropagation)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblAnimationTimeSpan, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAnimationTimeSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkAnimateLabelPropagation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnimationTimeSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnimationTimeSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkAnimateLabelPropagationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkAnimateLabelPropagationStateChanged
        txtAnimationTimeSpan.setEnabled(chkAnimateLabelPropagation.isSelected());
        lblAnimationTimeSpan.setEnabled(chkAnimateLabelPropagation.isSelected());
    }//GEN-LAST:event_chkAnimateLabelPropagationStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox chkAnimateLabelPropagation;
    private javax.swing.JLabel lblAnimationTimeSpan;
    public javax.swing.JFormattedTextField txtAnimationTimeSpan;
    // End of variables declaration//GEN-END:variables

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
